### ISSUE TITLE
extend .pre-commit-config.yaml with a prettier setup for the frontend

### ISSUE THREAD

**Issue by to-sta** [to-sta/cv_constructor#1]
<ins>Task</ins> is to setup the [pre-commit ](https://pre-commit.com/) hook to include prettier. I made a attempt myself that you can find in the [config file](https://github.com/to-sta/cv_constructor/blob/master/.pre-commit-config.yaml) at the moment:

```yaml
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v3.0.3
  hooks:
    - id: prettier
      files: ^frontend\/[^\/]+
      args: [--config, frontend/.prettierrc,--write]
      additional_dependencies:
        - prettier
        - "prettier-plugin-svelte@2.10.1"
        - svelte
```

But I am still getting an error `[error] Cannot find package 'prettier-plugin-svelte'`, even though I added prettier-plugin-svelte to the additional_dependencies. Maybe its an issue with the `.prettierrc` file. 

I would appreciate help with this issue. It's the last missing piece in the pre-commit setup.
